# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:

        cache: ~

        hero_image:
            filters:
                thumbnail:
                    size: [3000, 2000]
                    mode: inset

        featured_image:
            filters:
                thumbnail:
                    size: [1366, 716]
                    mode: inset

        featured_image_small:
            filters:
                thumbnail:
                    size: [600, 690]
                    mode: inset

        featured_image_thumbnail:
            filters:
                thumbnail:
                    size: [100, 70]
                    mode: inset

        user_thumb:
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: inset
